services:
  proxy:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - php-app

  php-app:
    image: wordpress:php8.3-fpm
    restart: on-failure
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4
    restart: on-failure
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './docker/php/data'
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './docker/mysql/data'